"""Centralized configuration package for OpenWispr.

This package provides a single source of truth for all configuration values,
text strings, and constants used throughout the application.
"""

# Settings registry (single source of truth for all settings)
from app.config.constants import (
    COMMON_FILLER_WORDS,
    GPU_FALLBACK_KEYWORDS,
    HALLUCINATION_CONFIDENCE_THRESHOLD,
    HALLUCINATION_PHRASES,
    LIVE_MODE_PROFILES,
    AudioCaptureConstants,
    AudioConstants,
    AutoOptimizationConstants,
    FastChunkerConstants,
    HealthConstants,
    ModelConstants,
    PerformanceConstants,
    QualityConstants,
    RefinerConstants,
    ServerConstants,
    SessionConstants,
    UIConstants,
    VADConstants,
)
from app.config.settings import (
    CURRENT_SETTINGS_VERSION,
    FAKE_SETTINGS,
    SETTINGS_REGISTRY,
    SettingDefinition,
    get_all_categories,
    get_all_defaults,
    get_category_defaults,
    get_fake_settings,
    get_setting,
    get_setting_default,
    get_settings_by_category,
    get_settings_version,
    validate_setting,
)
from app.config.text import (
    AUDIO_BACKEND_LABELS,
    BUTTON_LABELS,
    CAPTURE_MODE_LABELS,
    CATEGORY_LABELS,
    COMPUTE_TYPE_LABELS,
    ERROR_MESSAGES,
    FINISH_ACTION_LABELS,
    FLOATING_POSITION_LABELS,
    LIVE_MODE_DESCRIPTIONS,
    LIVE_MODE_LABELS,
    LOG_LEVEL_LABELS,
    MODEL_NAMES,
    OPTIMIZATION_PRESET_LABELS,
    PRESET_DESCRIPTIONS,
    REFINEMENT_MODE_LABELS,
    REFINER_ENGINE_LABELS,
    SAMPLE_RATE_LABELS,
    SECTION_HEADERS,
    SETTING_DESCRIPTIONS,
    SETTING_LABELS,
    STATUS_LABELS,
    TAB_LABELS,
    THEME_LABELS,
    TOOLTIPS,
)

__all__ = [
    # Settings
    "SETTINGS_REGISTRY",
    "FAKE_SETTINGS",
    "SettingDefinition",
    "get_setting",
    "get_settings_by_category",
    "get_all_categories",
    "get_fake_settings",
    "validate_setting",
    "get_setting_default",
    "get_category_defaults",
    "get_all_defaults",
    "get_settings_version",
    "CURRENT_SETTINGS_VERSION",
    # Constants classes
    "AudioConstants",
    "VADConstants",
    "ModelConstants",
    "PerformanceConstants",
    "SessionConstants",
    "UIConstants",
    "QualityConstants",
    "ServerConstants",
    "FastChunkerConstants",
    "AudioCaptureConstants",
    "HealthConstants",
    "AutoOptimizationConstants",
    "RefinerConstants",
    # Raw constants
    "LIVE_MODE_PROFILES",
    "COMMON_FILLER_WORDS",
    "HALLUCINATION_PHRASES",
    "HALLUCINATION_CONFIDENCE_THRESHOLD",
    "GPU_FALLBACK_KEYWORDS",
    # Text constants
    "MODEL_NAMES",
    "LIVE_MODE_LABELS",
    "LIVE_MODE_DESCRIPTIONS",
    "CATEGORY_LABELS",
    "SETTING_LABELS",
    "SETTING_DESCRIPTIONS",
    "ERROR_MESSAGES",
    "TOOLTIPS",
    "THEME_LABELS",
    "COMPUTE_TYPE_LABELS",
    "CAPTURE_MODE_LABELS",
    "AUDIO_BACKEND_LABELS",
    "SAMPLE_RATE_LABELS",
    "FINISH_ACTION_LABELS",
    "FLOATING_POSITION_LABELS",
    "LOG_LEVEL_LABELS",
    "OPTIMIZATION_PRESET_LABELS",
    "PRESET_DESCRIPTIONS",
    "REFINEMENT_MODE_LABELS",
    "REFINER_ENGINE_LABELS",
    "TAB_LABELS",
    "BUTTON_LABELS",
    "STATUS_LABELS",
    "SECTION_HEADERS",
]

