import type { OptimizationPreset } from './types';

export const PRESETS: OptimizationPreset[] = [
  {
    id: 'dictation',
    name: 'Dictation (Recommended)',
    description: 'Best default for microphone dictation, short phrases, and hotkey use',
    icon: 'mic',
    recommended_for: ['Microphone', 'Short dictation', 'Recommended'],
    settings_override: {
      model_name: 'medium',
      compute_type: 'float16',
      beam_size: 3,
      best_of: 3,
      patience: 1.0,
      temperature: 0.1,
      vad_threshold_db: -45,
      confidence_threshold: 0.35,
      chunk_duration: 1.4,
      overlap_ratio: 0.18,
      min_segment_length: 0.35,
      enable_filler_filter: false,
    },
  },
  {
    id: 'maximum',
    name: 'Maximum Quality',
    description: 'Best accuracy with largest model, slower processing',
    icon: 'award',
    recommended_for: ['High-end GPU', 'Accuracy critical'],
    settings_override: {
      model_name: 'large-v3',
      compute_type: 'float16',
      beam_size: 10,
      best_of: 10,
      patience: 2.0,
      temperature: 0.0,
      vad_threshold_db: -45,
      confidence_threshold: 0.7,
    },
  },
  {
    id: 'balanced',
    name: 'Balanced',
    description: 'Good balance of speed and accuracy',
    icon: 'scale',
    recommended_for: ['Most systems', 'General use'],
    settings_override: {
      model_name: 'medium',
      compute_type: 'float16',
      beam_size: 5,
      best_of: 5,
      patience: 1.0,
      temperature: 0.0,
      vad_threshold_db: -40,
      confidence_threshold: 0.6,
    },
  },
  {
    id: 'fast',
    name: 'Fast',
    description: 'Prioritizes speed over accuracy',
    icon: 'zap',
    recommended_for: ['Real-time use', 'Lower-end hardware'],
    settings_override: {
      model_name: 'small',
      compute_type: 'int8',
      beam_size: 3,
      best_of: 3,
      patience: 0.8,
      temperature: 0.2,
      vad_threshold_db: -35,
      confidence_threshold: 0.5,
      chunk_duration: 1.0,
    },
  },
  {
    id: 'low_memory',
    name: 'Low Memory',
    description: 'Minimal resource usage for limited systems',
    icon: 'feather',
    recommended_for: ['8GB RAM or less', 'CPU only'],
    settings_override: {
      model_name: 'tiny',
      compute_type: 'int8',
      beam_size: 1,
      best_of: 1,
      patience: 0.5,
      temperature: 0.4,
      vad_threshold_db: -30,
      confidence_threshold: 0.4,
      chunk_duration: 0.8,
      use_parallel_processing: false,
      preload_model: false,
    },
  },
];
