import {
  CAPTURE_MODE_LABELS,
  COMPUTE_TYPE_LABELS,
  LOG_LEVEL_LABELS,
  REFINEMENT_MODE_LABELS,
  REFINEMENT_PROFILE_LABELS,
  SETTING_DESCRIPTIONS,
  SETTINGS_SECTION_TEXT,
} from '../config/text';

export const RENDERER_STRINGS = {
  settings: {
    common: {
      browse: 'Browse',
      comingSoon: 'Coming Soon',
      custom: 'Custom',
      unassigned: 'Unassigned',
      unknown: 'Unknown',
      latest: 'Latest',
      release: 'Release',
      loadingPreview: 'Loading preview…',
      previewUnavailable: 'Preview unavailable',
      enableCustomPrompt: 'Enable custom prompt',
      systemPrompt: 'System prompt',
      userPrompt: 'User prompt',
    },
    categories: {
      general: {
        label: 'General',
        description: 'Session defaults, language, export location',
      },
      models: {
        label: 'Models',
        description: 'Download, verify, and select ASR and refiner models',
      },
      transcription: {
        label: 'Transcription',
        description: 'Profiles, language, finish behavior, and cleanup',
      },
      audio: {
        label: 'Audio',
        description: 'VAD, noise filtering, audio devices',
      },
      hotkey: {
        label: 'Hotkey',
        description: 'Global shortcut configuration',
      },
      coach: {
        label: 'Coach',
        description: 'Optional English improvement after dictation finishes',
      },
      history: {
        label: 'History',
        description: 'Retention, retry, and analytics defaults',
      },
      dictionary: {
        label: 'Dictionary',
        description: 'Replacement and phrase rules',
      },
      snippets: {
        label: 'Snippets',
        description: 'Trigger expansion controls',
      },
      style: {
        label: 'Writing Tone',
        description: 'Optional tone shaping for final text after cleanup',
      },
      advanced: {
        label: 'Advanced',
        description: 'Expert settings, developer options',
      },
    },
    general: {
      title: 'General Settings',
      description: 'Configure default session behavior and application preferences',
      themeTitle: 'Theme',
      themeDescription: 'Application color theme',
      defaultSessionTitle: 'Default Session Title',
      defaultSessionDescription: 'Default name for new transcription sessions',
      defaultLanguageTitle: 'Default Language',
      defaultLanguageDescription: 'Primary language for transcription (auto-detects if set to Auto)',
      exportDirectoryTitle: 'Export Directory',
      exportDirectoryDescription: 'Default location for exported transcripts and files',
      exportDirectoryPlaceholder: 'Use default documents folder',
      autoSaveTitle: 'Auto-save Interval',
      autoSaveDescription: 'How often to automatically save session progress (in seconds)',
      behaviorTitle: 'Application Behavior',
      showNotificationsTitle: 'Show Notifications',
      showNotificationsDescription: 'Display desktop notifications for events',
      minimizeToTrayTitle: 'Minimize to Tray',
      minimizeToTrayDescription: 'Keep running in system tray when closed',
      startupWithSystemTitle: 'Start with System',
      startupWithSystemDescription: 'Launch automatically on Windows startup',
      themeOptions: [
        { value: 'light', label: 'Light (Lawn)' },
        { value: 'dark', label: 'Dark (Night)' },
        { value: 'cyber', label: 'Cyberpunk' },
        { value: 'dracula', label: 'Dracula' },
        { value: 'ocean', label: 'Ocean' },
        { value: 'sunset', label: 'Sunset' },
        { value: 'forest', label: 'Forest' },
      ],
    },
    transcription: {
      micLanguageTitle: 'Mic Dictation Language',
      micLanguageDescription: 'Language used for microphone hotkey dictation. Use Auto only if you want language detection.',
      modeTitle: 'Transcription Mode',
      modeDescription: 'Dictation keeps prose conservative. Literal preserves technical tokens, digits, and spoken symbols more aggressively.',
      modeOptions: [
        { value: 'dictation', label: 'Dictation' },
        { value: 'literal', label: 'Literal' },
        { value: 'session_paragraph', label: 'Session Paragraph' },
      ],
      profileSummaryLabels: {
        preset: 'Preset',
        language: 'Language',
        finish: 'Finish',
        refinement: 'Cleanup',
        microphone: 'Microphone',
        systemAudio: 'System Audio',
      },
      finishModeOptions: [
        { value: 'finish', label: 'Finish Only' },
        { value: 'finish_and_paste', label: 'Finish & Paste' },
        { value: 'cancel', label: 'Cancel' },
      ],
      refinerEnabledHint: (modelId: string | null | undefined) =>
        `Uses ${modelId || 'the selected local refiner'} when enabled.`,
      refinerDisabledHint: 'Runtime is currently disabled in Models, so this stays deterministic-only.',
      cleanupPlaceholder:
        'Example: keep technical tokens exact, improve punctuation, and preserve line order.',
      advancedTuningTitle: 'Advanced Tuning',
      advancedTuningDescription:
        'Keep these on defaults unless you are troubleshooting quality, latency, or memory usage.',
      showAdvanced: 'Show',
      hideAdvanced: 'Hide',
      computeTypeOptions: [
        { value: 'float16', label: COMPUTE_TYPE_LABELS.float16 },
        { value: 'int8', label: COMPUTE_TYPE_LABELS.int8 },
        { value: 'int8_float16', label: COMPUTE_TYPE_LABELS.int8_float16 },
      ],
      refinementModeOptions: [
        { value: 'off', label: REFINEMENT_MODE_LABELS.off },
        { value: 'strict', label: REFINEMENT_MODE_LABELS.strict },
        { value: 'polished', label: REFINEMENT_MODE_LABELS.polished },
      ],
      refinementProfileOptions: [
        { value: 'raw', label: REFINEMENT_PROFILE_LABELS.raw },
        { value: 'clean_dictation', label: REFINEMENT_PROFILE_LABELS.clean_dictation },
        { value: 'professional', label: REFINEMENT_PROFILE_LABELS.professional },
        { value: 'student_notes', label: REFINEMENT_PROFILE_LABELS.student_notes },
        { value: 'code_logs', label: REFINEMENT_PROFILE_LABELS.code_logs },
      ],
    },
    models: {
      engineCards: {
        asrTitle: 'ASR Engine',
        asrRuntime: 'faster-whisper (local)',
        asrDescription: 'Whisper checkpoints run through the faster-whisper engine for local speech-to-text.',
        refinerTitle: 'Refiner Runtime',
        refinerRuntime: 'llama.cpp (local)',
        refinerDescription: 'Used only for final cleanup. Partial text never goes through the refiner.',
      },
    },
    hotkey: {
      title: 'Hotkey Configuration',
      description: 'Configure global keyboard shortcuts for quick access',
      enableTitle: 'Enable Global Hotkey',
      enableDescription: 'Activate transcription from anywhere',
      microphoneHotkeyTitle: 'Microphone Hotkey',
      microphoneHotkeyDescription: 'Global shortcut for microphone dictation',
      systemHotkeyTitle: 'System Audio Hotkey',
      systemHotkeyDescription: 'Global shortcut for loopback/system audio transcription',
      captureSourceTitle: 'Hotkey Capture Source',
      captureSourceDescription: 'Choose whether the hotkey records your microphone or system audio',
      captureSourceOptions: [
        { value: 'microphone', label: 'Microphone' },
        { value: 'system', label: 'System Audio' },
      ],
      systemDeviceTitle: 'System Audio Device',
      systemDeviceDescription: 'Loopback device used for quick system-audio transcription',
      microphoneDeviceTitle: 'Dictation Microphone',
      microphoneDeviceDescription: 'Microphone source used for quick dictation',
      autoDetectSystemAudio: 'Auto-detect system audio',
      autoDetectMicrophone: 'Auto-detect microphone',
      floatingPositionTitle: 'Floating Window Position',
      floatingPositionDescription: 'Where to show the transcription overlay',
      floatingPositionOptions: [
        { value: 'top-left', label: 'Top Left' },
        { value: 'top-right', label: 'Top Right' },
        { value: 'bottom-left', label: 'Bottom Left' },
        { value: 'bottom-right', label: 'Bottom Right' },
        { value: 'center', label: 'Center' },
      ],
      behaviorTitle: 'Hotkey Behavior',
      behavior: {
        holdMode: {
          title: 'Hold Mode',
          description: 'Record while holding the hotkey',
        },
        autoInject: {
          title: 'Auto-inject Text',
          description: 'Type transcription into active window',
        },
        showFloatingWindow: {
          title: 'Show Floating Window',
          description: 'Display overlay during transcription',
        },
        saveDebugWav: {
          title: 'Save Hotkey Debug WAV',
          description: 'Write captured dictation audio to logs/hotkey-debug',
        },
        copyToClipboard: {
          title: 'Copy to Clipboard',
          description: 'Automatically copy transcription',
        },
        recordOnStart: {
          title: 'Record on Start',
          description: 'Automatically start recording when hotkey session begins',
        },
        stopOnRelease: {
          title: 'Stop on Release',
          description: 'Stop recording when hotkey is released (hold mode)',
        },
      },
    },
    audio: {
      recordingDeviceSuffix: ' [rec]',
      muteOpenWisprAudioDuringDictationTitle: 'Mute app audio during transcription',
      muteOpenWisprAudioDuringDictationDescription:
                SETTING_DESCRIPTIONS.mute_openwispr_audio_during_dictation + ' Disabled by default.',
    },
    advanced: {
      title: 'Advanced Settings',
      description: 'Expert configuration and developer options',
      warningTitle: 'Warning',
      warningDescription:
        'These settings are intended for advanced users. Incorrect values may cause instability or poor performance.',
      errorTitle: 'Error',
      debuggingTitle: 'Debugging',
      debugModeTitle: 'Debug Mode',
      debugModeDescription: 'Enable verbose logging and diagnostics',
      maxLogFilesTitle: 'Max Log Files',
      maxLogFilesDescription: 'Number of log files to retain',
      logLevelTitle: 'Log Level',
      logLevelDescription: 'Minimum severity for log messages',
      logLevelOptions: [
        { value: 'DEBUG', label: LOG_LEVEL_LABELS.DEBUG },
        { value: 'INFO', label: LOG_LEVEL_LABELS.INFO },
        { value: 'WARN', label: LOG_LEVEL_LABELS.WARN },
        { value: 'ERROR', label: LOG_LEVEL_LABELS.ERROR },
      ],
      experimentalTitle: 'Experimental Features',
      enhancedStemTitle: 'Enhanced STEM Detection',
      enhancedStemDescription: 'Advanced formula and equation recognition',
      gpuAccelerationTitle: 'GPU Acceleration',
      gpuAccelerationDescription: 'Use GPU for pre-processing when available',
      metricsTitle: 'Enable Metrics',
      metricsDescription: 'Collect and report performance metrics',
      appInfoTitle: 'Application Info',
      appInfoLabels: {
        version: 'Version',
        platform: 'Platform',
        build: 'Build',
      },
    },
    coach: {
      title: 'English Coach',
      description:
        'Improve English after dictation stops with optional polished text, fixes, and prompt preview.',
      sampleOriginalText:
        'Please rewrite this sample transcript into a cleaner final paragraph while preserving meaning.',
      previewUnavailable: 'Preview unavailable',
      enableTitle: 'Enable English Coach',
      enableDescription: 'Run the optional coaching stage after microphone dictation finalizes.',
      privacyModeTitle: 'Privacy Mode',
      privacyModeDescription:
        'Local only keeps the final transcript deterministic. Allow LLM enables coached JSON output.',
      privacyModeOptions: [
        { value: 'local_only', label: 'Local only' },
        { value: 'allow_llm', label: 'Allow local LLM' },
      ],
      localOnlyWarningTitle: 'Coach is in fallback-only mode',
      localOnlyWarningDescription:
        'Switch Privacy Mode to Allow local LLM if you want polished coach output instead of the faithful transcript.',
      runtimeDisabledWarningTitle: 'Coach runtime is disabled',
      runtimeDisabledWarningDescription:
        'Enable the Refiner runtime and install a local coach model if you want the coach stage to produce polished output.',
      detailLevelTitle: 'Coach Detail Level',
      detailLevelDescription: 'Choose how much feedback appears in the Coach panel and floating summary.',
      detailLevelOptions: [
        { value: 'compact', label: 'Compact' },
        { value: 'standard', label: 'Standard' },
        { value: 'deep', label: 'Deep' },
      ],
      templateTitle: 'Microphone Coach Template',
      templateDescription: 'Prompt template used when coaching microphone dictation.',
      outputTitle: 'Coach Output',
      pastePolishedTitle: 'Paste polished text by default',
      pastePolishedDescription:
        'If coaching succeeds, paste the polished paragraph instead of the raw final transcript.',
      showDiffTitle: 'Show diff view',
      showDiffDescription:
        'Render edit operations between the aggregated transcript and the polished version.',
      showFloatingResultTitle: 'Show floating coach result',
      showFloatingResultDescription:
        'Keep the floating window visible after stop with a compact result summary.',
      toneTitle: 'Tone',
      toneDescription: 'The overall coaching voice injected into the prompt.',
      toneOptions: [
        { value: 'neutral', label: 'Neutral' },
        { value: 'friendly', label: 'Friendly' },
        { value: 'strict', label: 'Strict' },
      ],
      aggressivenessTitle: 'Aggressiveness',
      aggressivenessDescription:
        'How strongly the coach should rewrite wording while preserving meaning.',
      aggressivenessOptions: [
        { value: 'light', label: 'Light' },
        { value: 'medium', label: 'Medium' },
        { value: 'strong', label: 'Strong' },
      ],
      fillerRemovalTitle: 'Filler removal',
      fillerRemovalDescription:
        'Remove low-value filler only when it does not change meaning.',
      keepSlangTitle: 'Keep slang',
      keepSlangDescription: 'Preserve casual wording when it fits the original tone.',
      targetStyleTitle: 'Target style',
      targetStyleDescription: 'Preferred style for the polished output.',
      targetStyleOptions: [
        { value: 'simple', label: 'Simple' },
        { value: 'chat', label: 'Chat' },
        { value: 'email', label: 'Email' },
        { value: 'formal', label: 'Formal' },
      ],
      customPromptTitle: 'Custom user prompt',
      customPromptDescription:
        'Override only the user prompt section while keeping the built-in system instructions.',
      promptPreviewTitle: 'Prompt preview',
      promptPreviewDescription:
        'Backend-compiled preview of the exact prompt payload that will be sent at stop.',
    },
    provider: {
      title: 'Local LLM Provider',
      description: 'Check the status of local LLM inference engines.',
      statusTitle: 'Provider Status',
      statusDescription: 'Health check results for available LLM providers.',
      ollama: 'Ollama',
      lmStudio: 'LM Studio',
      llamaCpp: 'Llama.cpp',
      available: 'Available',
      unavailable: 'Unavailable',
      checking: 'Checking...',
      responseTime: 'Response time',
      error: 'Error',
      refreshButton: 'Refresh',
    },
    history: {
      title: 'History Settings',
      description: 'Configure transcript retention, retry behavior, and analytics defaults.',
      retentionDaysTitle: 'Retention Days',
      retentionDaysDescription: 'Soft-delete transcript sessions after this many days.',
      defaultRangeTitle: 'Default Analytics Range',
      defaultRangeDescription: 'Default range for Home analytics on launch.',
      defaultRangeOptions: [
        { value: '7', label: 'Last 7 days' },
        { value: '30', label: 'Last 30 days' },
        { value: '90', label: 'Last 90 days' },
        { value: 'all', label: 'All time' },
      ],
      persistAudioTitle: 'Persist Audio',
      persistAudioDescription: 'Keep recorded audio to enable audio download and retry.',
      allowRetryTitle: 'Allow Retry',
      allowRetryDescription: 'Allow rerunning transcript generation from retained audio.',
    },
    dictionary: {
      title: 'Dictionary Settings',
      description: 'Configure deterministic phrase replacement behavior.',
      enableTitle: 'Enable Dictionary',
      enableDescription: 'Apply dictionary replacements during transcript finalization.',
    },
    snippets: {
      title: 'Snippets Settings',
      description: 'Configure snippet expansion behavior.',
      enableTitle: 'Enable Snippets',
      enableDescription: 'Expand snippet triggers while finalizing transcripts.',
      quickInsertTitle: 'Quick Insert',
      quickInsertDescription: 'Prefer snippet expansion in copy/paste output composition.',
    },
    style: {
      title: 'Writing Tone',
      description: 'Optional tone shaping for final text after transcript cleanup has already finished.',
      enableTitle: 'Enable writing tone',
      enableDescription: 'Apply an optional tone profile to final output after cleanup and before paste/copy.',
      enableHint: 'Keep this off unless you want the final wording to sound more formal or casual.',
      disabledHint: 'Transcript cleanup still works with writing tone off.',
      defaultProfileTitle: 'Default tone profile',
      defaultProfileDescription: 'Fallback tone when no context-specific assignment exists.',
      defaultProfileOptions: [
        { value: 'formal', label: 'Formal' },
        { value: 'casual', label: 'Casual' },
        { value: 'very_casual', label: 'Very Casual' },
      ],
      contextTitle: 'Context assignments',
      contextDescription: 'Choose which profile each writing context should use.',
      contextOptions: { personal: 'Personal', work: 'Work', email: 'Email', other: 'Other' },
      activeProfileLabel: 'Active profile',
      none: 'None',
      previewTitle: 'Tone preview',
      previewDescription: 'Preview how the current writing tone changes final wording. This does not affect recognition accuracy.',
      previewButton: 'Preview tone',
      noPreview: 'No preview yet',
      loading: 'Loading…',
      libraryTitle: 'Tone library',
      libraryDescription: 'Built-in tones stay simple. Custom profiles live under Advanced.',
      emptyLibrary: 'No tone profiles found yet.',
      setActiveButton: 'Set active',
      deleteButton: 'Delete',
      advancedTitle: 'Advanced profile editor',
      advancedDescription: 'Only open this if you need custom profiles or raw rule editing.',
      showAdvanced: 'Show advanced',
      hideAdvanced: 'Hide advanced',
      createTitle: 'Create custom profile',
      createDescription: 'Add a custom writing tone without cluttering the main settings flow.',
      createError: 'Unable to create profile',
      profileNamePlaceholder: 'Profile name',
      addButton: 'Add profile',
      editorTitle: 'Selected profile',
      editorDescription: 'Built-in profiles are simple. Custom profiles can be edited here.',
      enabledCheckbox: 'Enabled',
      saveButton: 'Save profile',
      selectProfile: 'Select a profile to edit.',
      savedMessage: 'Saved',
      invalidRules: 'Invalid rule JSON',
      loadError: 'Unable to load tone profiles',
      assignmentError: 'Unable to update context assignment',
      previewError: 'Unable to preview tone',
      deleteError: 'Unable to delete profile',
      customDescription: (name: string) => `${name} tone profile`,
      defaultPreviewInput: 'hey are you free tomorrow lets do lunch',
    },
    generated: {
      sectionText: SETTINGS_SECTION_TEXT,
      captureModeLabels: CAPTURE_MODE_LABELS,
      computeTypeLabels: COMPUTE_TYPE_LABELS,
      refinementModeLabels: REFINEMENT_MODE_LABELS,
      refinementProfileLabels: REFINEMENT_PROFILE_LABELS,
    },
  },
  appSidebar: {
    heroEyebrow: 'Privacy-first local transcription',
    heroBody: 'Home tracks analytics and session history. Microphone and system audio stay as dedicated workspaces.',
    pageMeta: {
      home: { label: 'Home', eyebrow: 'Analytics + history' },
      microphone: { label: 'Microphone', eyebrow: 'Live dictation' },
      systemAudio: { label: 'System Audio', eyebrow: 'Long-form capture' },
      dictionary: { label: 'Dictionary', eyebrow: 'Replacement rules' },
      snippets: { label: 'Snippets', eyebrow: 'Trigger expansions' },
      settings: { label: 'Settings', eyebrow: 'Defaults / advanced' },
    },
    connection: {
      liveStream: 'Live stream',
      reconnecting: 'Reconnecting',
      pollingFallback: 'Polling fallback',
    },
    gpu: {
      active: 'GPU active',
      failed: 'GPU only failed',
      fallback: 'CPU fallback',
    },
    controls: {
      refreshDevices: 'Refresh devices',
    },
    sessionStatus: 'Session status',
    runtime: 'Runtime',
  },
  pages: {
    home: {
      title: 'Home',
      subtitle: 'Usage analytics and transcript history',
      compactTitle: 'Usage at a glance',
      compactSubtitle: 'Recent dictation performance and transcript actions without leaving the microphone workspace.',
      rangeOptions: {
        last7: 'Last 7 days',
        last30: 'Last 30 days',
        last90: 'Last 90 days',
        all: 'All time',
      },
      settingsButton: 'Settings',
      metrics: {
        daysUsed: 'Days used',
        totalWords: 'Total words',
        avgWpm: 'Avg WPM',
        peakHour: 'Peak hour',
      },
      dailyUsage: 'Daily usage',
      hourHeat: 'Hour-of-day heat',
      noData: 'No data yet',
      sessionsTitle: 'Transcript sessions',
      loading: 'Loading...',
      noSessions: 'No sessions yet.',
      sourceSeparator: '·',
      modelUnknown: 'model unknown',
      wordsSuffix: 'words',
      actions: {
        copy: 'Copy transcript',
        undoAiEdit: 'Undo AI edit',
        retry: 'Retry transcript',
        downloadAudio: 'Download audio',
        downloadTranscript: 'Download transcript',
        delete: 'Delete transcript',
      },
      status: {
        copied: 'Transcript copied',
        aiUndone: 'AI edit undone',
        retryStarted: 'Retry started',
        deleted: 'Transcript deleted',
        failedLoad: 'Failed to load home data',
        failedAction: 'Action failed',
        failedDownload: 'Download failed',
        downloadedAudio: 'Audio downloaded',
        downloadedTranscript: 'Transcript downloaded',
      },
    },
    dictionary: {
      title: 'Dictionary',
      subtitle: 'Deterministic phrase replacements',
      enabled: 'Enabled',
      disabled: 'Disabled in settings',
      tabs: {
        all: 'All',
        personal: 'Personal',
        shared: 'Shared with team',
        team: 'Team',
      },
      searchPlaceholder: 'Search phrase or replacement',
      searchButton: 'Search',
      addTitle: 'Add entry',
      phrasePlaceholder: 'Phrase',
      replacementPlaceholder: 'Replacement',
      addButton: 'Add',
      previewTitle: 'Preview',
      previewPlaceholder: 'Try an input phrase',
      previewButton: 'Preview',
      noPreview: 'No preview yet',
      usesSuffix: 'uses',
      deleteButton: 'Delete',
      noEntries: 'No entries yet.',
    },
    snippets: {
      title: 'Snippets',
      subtitle: 'Trigger-based text expansion',
      enabled: 'Enabled',
      disabled: 'Disabled in settings',
      tabs: {
        all: 'All',
        personal: 'Personal',
        shared: 'Shared with team',
        team: 'Team',
      },
      addTitle: 'Add snippet',
      triggerPlaceholder: 'Trigger',
      expansionPlaceholder: 'Expansion',
      addButton: 'Add',
      previewTitle: 'Preview',
      previewPlaceholder: 'Type text with snippet triggers',
      previewButton: 'Preview',
      noPreview: 'No preview yet',
      exportButton: 'Export JSON',
      importButton: 'Import JSON',
      usesSuffix: 'uses',
      deleteButton: 'Delete',
      noEntries: 'No snippets yet.',
    },
    style: {
      title: 'Style',
      subtitle: 'Context-specific output style profiles',
      enabled: 'Enabled',
      disabled: 'Disabled in settings',
      contextTitle: 'Context',
      activeProfile: 'Active profile',
      none: 'None',
      previewTitle: 'Preview',
      previewButton: 'Preview active',
      noPreview: 'No preview yet',
      createTitle: 'Create profile',
      profileNamePlaceholder: 'Profile name',
      addButton: 'Add',
      setActiveButton: 'Set active',
      deleteButton: 'Delete',
      defaultPreviewInput: 'hey are you free tomorrow lets do lunch',
    },
  },
  mainContent: {
    panels: {
      combined: 'Combined',
      coach: 'Coach',
    },
    combined: {
      inlineLabel: 'Combined Live Transcript',
      inlineEmpty: 'Combined text appears here while dictation is active.',
      panelTitle: 'Combined Dictation',
      emptyTitle: 'No combined transcript yet',
      emptyBody:
        'Start dictation to build one combined transcript for this hotkey run. Segment cards remain available in the timeline.',
    },
    coach: {
      diffTitle: 'Edit Diff',
      fromLabel: 'From',
      toLabel: 'To',
      emptyToken: '(empty)',
      diffOps: {
        insert: 'Insert',
        replace: 'Replace',
        delete: 'Delete',
      },
    },
  },
} as const;




